version: '3.5'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "readme-blogs"
    ports:
      - "5444:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "keks@htmlacademy.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    ports:
      - "8082:80"
    restart: unless-stopped
    networks:
      - postgres

  readme.blogs:
    image: readme.blogs
    depends_on:
      - pgadmin
      - postgres
    container_name: readme.blogs.service
    ports:
      - 3334:3333
    environment:
      DATABASE_URL: postgresql://admin:test@postgres:5432/readme-blogs?schema=public
      UPLOAD_DIR: upload

networks:
  postgres:
    driver: bridge
