###
# Get comment by ID
GET http://localhost:3334/api/comments/4 HTTP/1.1

###

# Get list of comments
GET http://localhost:3334/api/comments?postId=5 HTTP/1.1
Content-Type: application/json

###

# Create a new comment
POST http://localhost:3334/api/comments HTTP/1.1
Content-Type: application/json

{
  "postId": 5,
  "text": "good for monkeys",
  "userId": "63a0d94977a490b106e87e43"
}

###

# Delete a comment
DELETE http://localhost:3334/api/comments/4/63a0d94977a490b106e87e43 HTTP/1.1

###

